name: Release Artifacts
on:
    release:
        types: [published]
jobs:
    tarballs:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6
            - name: Package tarballs
              run: |
                cd src
                find * -type d -execdir tar -caf devcontainer-feature-{}.tgz -C {} ./ \;
            - name: Upload artifacts
              run: |
                gh release upload ${GITHUB_REF_NAME} --clobber *.tgz
              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                GH_REPO: ${{ github.repository }}
