name: Release Artifacts
on:
    release:
        types: [published]
jobs:
    tarballs:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6
            - name: Package tarballs
              run: |
                cd src
                for dir in *; do tar caf ${dir}-${GITHUB_REF_NAME}.tar.gz $dir/*; done
                gh release upload ${GITHUB_REF_NAME} --clobber *.tar.gz
              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                GH_REPO: ${{ github.repository }}